### ISSUE TITLE
Question: Are previous base zoning district maps available anywhere?

### ISSUE THREAD

**Issue by kettle11** [opendataphilly/opendataphilly-jkan#131]
I've wanted to analyze how the city has changed zoning over the last decade and unfortunately I can only find files for today's base zoning districts. This is the data I see that's available: https://opendataphilly.org/datasets/zoning-base-districts/

Does anyone know if there's a way to access previous versions of that data?

**Comment by seanmc5943** [comment]
I am also interested in the older archived versions of the city zoning districts!

**Comment by rcheetham** [comment]
@kettle11 @seanmc5943 The City doesn't publish historic data, but I think I might have the data you are seeking in my personal archives. I've created an issue to track this work at #232

**Comment by rcheetham** [comment]
@kettle11 @seanmc5943 I was able to find some historic zoning data sets that preceded the 2012 zoning reform project and these updates to the data catalog are attached to pull request #231. I've made the data available at https://github.com/opendataphilly/open-geo-data/

**Comment by kettle11** [comment]
@rcheetham I'd like to leave this issue open, or I will open a new issue because I still think it's important to be able to see more granular revisions through the years. 

A year to year change would be very useful for analyzing policy evolution with time.

**Comment by rcheetham** [comment]
@kettle11 If you'd like to request an annual set of zoning base map revisions, that seems like a new issue, and I would recommend outlining that request. However, the OpenDataPhilly technology team (which is made up of volunteers) will not be able to respond directly, and it will be up to the City if they want to make that dataset enhancement. The most direct way to access a granular dataset of this type would be to make the request via a formal Open Records Request. There is more information on how to do make an Open Records Request at https://www.phila.gov/open-records-policy/. The Zoning Base Maps are maintained by the City Planning Commission, so you would submit the request to the Right To Know contact for that agency (currently Feige Grundman, Chief Deputy City Solicitor, Law Dept [RightToKnowLaw@phila.gov](mailto:RightToKnowLaw@phila.gov) )  The default Right to Know request form is at https://www.openrecords.pa.gov/Documents/RTKL/RTKRequestForm.pdf.

**Comment by kettle11** [comment]
@Kistine Wow that’s fantastic! Thanks for the heads up.
