### ISSUE TITLE
Recent dataset page 404

### ISSUE THREAD

**Issue by ctchadwick** [opendataphilly/opendataphilly-jkan#261]
Not sure if this is the correct place to inquire, but the link for the Licenses and Inspections Building Permits page at the URL: https://opendataphilly.org/datasets/licenses-and-inspections-building-permits is resulting in a 404 today (07-29-2024).  I check this page weekly and pull a table of permits and noticed this week (not prior weeks) it lands on a 404.  Is this dataset not available anymore?  If not is there any indication as to why it is not longer available and is there a comparable replacement set?  Any insight would be appreciated.

**Comment by BryanQuigley** [comment]
is it this page? https://opendataphilly.org/datasets/licenses-and-inspections-building-and-zoning-permits/

**Comment by ctchadwick** [comment]
That is the page.  It was definitely giving a 404 yesterday, I checked from several devices (windows and linux), two local and one in a data center and got the 404.  Thanks for following up Bryan.

**Comment by lydiascarf** [comment]
@BryanQuigley should we look into plugins for aliases? i think jekyll doesn't have aliases, but it would be nice to be able to slot these in as they come up

https://github.com/jekyll/jekyll-redirect-from

**Comment by ctchadwick** [comment]
Maybe I spoke to soon.  The data being returned on the query links (such as [L&I Building & Zoning Permits - 2016 to present (CSV)]) only shows data up to mid March 2020.  It was definitely showing data from 2024 on 07-21-2024.

**Comment by rcheetham** [comment]
@ctchadwick I tried as well and I'm confirming that there is no recent data anymore.  Please send an email to info@opendataphilly.org and I'll forward to a couple of people at the City with cc to you.

**Comment by rcheetham** [comment]
Opened a new data issue at #263
