### ISSUE TITLE
Add a CODEOWNERS file

### ISSUE THREAD

**Issue by lydiascarf** [opendataphilly/opendataphilly-jkan#65]
We want a CODEOWNERS file that will automatically request a maintainer-reviewer on each PR, and additionally request someone from the city whenever a city dataset or the city org is modified.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by adamdmharvey** [comment]
I believe this one may be good to close, @lydiascarf ?  Nice one! 👏🏻

**Comment by BryanQuigley** [comment]
@rcheetham @Kistine 

I'm thinking about making you both code owners for all datasets.  Still requiring reviews - but this way any dataset changes have more reviewers available.  CI passing would still be a requirement - so the changes should not be able to break the site.  

Thoughts?

**Comment by BryanQuigley** [comment]
We originally wanted to be more selective - but that's way too difficult.

**Comment by rcheetham** [comment]
+1
