### ISSUE TITLE
HTML tags in dataset entries are rendered as text

### ISSUE THREAD

**Issue by rcheetham** [opendataphilly/opendataphilly-jkan#67]
There are HTML tags (and possibly some markdown) in dataset descriptions. These are being display as HTML, rather than interpreted.

I don't know if we should treat this as a bug or find a way to strip out all of the tags and replace them with line breaks. Some examples in search results and on a data set page below:

![image](https://github.com/azavea/opendataphilly-jkan/assets/595431/b29229a0-0469-407b-a58c-a306f3e4204a)

![image](https://github.com/azavea/opendataphilly-jkan/assets/595431/341ea533-5762-411e-9afd-e93a80b8a76e)

**Comment by BryanQuigley** [comment]
AFAICT from my grep this is only septa datasets and one "Bike Network - Supporting Datasets"

Supporting in-line HTML in markdown is more complicated and I think this should just be removed/modified to be markdown.

**Comment by arigas2** [comment]
My understanding for how these markdown files are created, is that they were created from the import process from CKAN. Going forward, a new dataset markdown file would be created manually. Is this understanding correct?

**Comment by rcheetham** [comment]
@BryanQuigley I think this might be fixed. I did a lot of editing on SEPTA this weekend and HTML tags seem to be rendering ok. I also checked the referenced "Bike Network" data set and it seems to be fine.

**Comment by BryanQuigley** [comment]
< /br > above. Yes it seems to be mostly fixed but seems to be a strick subset of tags, but that seems fine.
